//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Entity", "FK_accounts", "emails", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MaiableMe.Data.email), "accounts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MaiableMe.Data.account), true)]
[assembly: EdmRelationshipAttribute("Entity", "FK_AccountSecurityQuestions", "accounts", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MaiableMe.Data.account), "accountsecurityquestions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MaiableMe.Data.accountsecurityquestion), true)]
[assembly: EdmRelationshipAttribute("Entity", "FK_AccountSecurityQuestions_SecurityQuestionID", "securityquestions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MaiableMe.Data.securityquestion), "accountsecurityquestions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MaiableMe.Data.accountsecurityquestion), true)]

#endregion

namespace MaiableMe.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MailableMeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MailableMeEntities object using the connection string found in the 'MailableMeEntities' section of the application configuration file.
        /// </summary>
        public MailableMeEntities() : base("name=MailableMeEntities", "MailableMeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MailableMeEntities object.
        /// </summary>
        public MailableMeEntities(string connectionString) : base(connectionString, "MailableMeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MailableMeEntities object.
        /// </summary>
        public MailableMeEntities(EntityConnection connection) : base(connection, "MailableMeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<account> accounts
        {
            get
            {
                if ((_accounts == null))
                {
                    _accounts = base.CreateObjectSet<account>("accounts");
                }
                return _accounts;
            }
        }
        private ObjectSet<account> _accounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accountsecurityquestion> accountsecurityquestions
        {
            get
            {
                if ((_accountsecurityquestions == null))
                {
                    _accountsecurityquestions = base.CreateObjectSet<accountsecurityquestion>("accountsecurityquestions");
                }
                return _accountsecurityquestions;
            }
        }
        private ObjectSet<accountsecurityquestion> _accountsecurityquestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<blog> blogs
        {
            get
            {
                if ((_blogs == null))
                {
                    _blogs = base.CreateObjectSet<blog>("blogs");
                }
                return _blogs;
            }
        }
        private ObjectSet<blog> _blogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<email> emails
        {
            get
            {
                if ((_emails == null))
                {
                    _emails = base.CreateObjectSet<email>("emails");
                }
                return _emails;
            }
        }
        private ObjectSet<email> _emails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<securityquestion> securityquestions
        {
            get
            {
                if ((_securityquestions == null))
                {
                    _securityquestions = base.CreateObjectSet<securityquestion>("securityquestions");
                }
                return _securityquestions;
            }
        }
        private ObjectSet<securityquestion> _securityquestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccounts(account account)
        {
            base.AddObject("accounts", account);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accountsecurityquestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccountsecurityquestions(accountsecurityquestion accountsecurityquestion)
        {
            base.AddObject("accountsecurityquestions", accountsecurityquestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the blogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToblogs(blog blog)
        {
            base.AddObject("blogs", blog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the emails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemails(email email)
        {
            base.AddObject("emails", email);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the securityquestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosecurityquestions(securityquestion securityquestion)
        {
            base.AddObject("securityquestions", securityquestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new account object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fullName">Initial value of the FullName property.</param>
        /// <param name="emailID">Initial value of the EmailID property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="birthDay">Initial value of the BirthDay property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static account Createaccount(global::System.Int32 id, global::System.String fullName, global::System.Int32 emailID, global::System.String password, global::System.String gender, global::System.DateTime birthDay, global::System.String address)
        {
            account account = new account();
            account.ID = id;
            account.FullName = fullName;
            account.EmailID = emailID;
            account.Password = password;
            account.Gender = gender;
            account.BirthDay = birthDay;
            account.Address = address;
            return account;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailUser
        {
            get
            {
                return _EmailUser;
            }
            set
            {
                OnEmailUserChanging(value);
                ReportPropertyChanging("EmailUser");
                _EmailUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailUser");
                OnEmailUserChanged();
            }
        }
        private global::System.String _EmailUser;
        partial void OnEmailUserChanging(global::System.String value);
        partial void OnEmailUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmailID
        {
            get
            {
                return _EmailID;
            }
            set
            {
                OnEmailIDChanging(value);
                ReportPropertyChanging("EmailID");
                _EmailID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmailID");
                OnEmailIDChanged();
            }
        }
        private global::System.Int32 _EmailID;
        partial void OnEmailIDChanging(global::System.Int32 value);
        partial void OnEmailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BirthDay
        {
            get
            {
                return _BirthDay;
            }
            set
            {
                OnBirthDayChanging(value);
                ReportPropertyChanging("BirthDay");
                _BirthDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BirthDay");
                OnBirthDayChanged();
            }
        }
        private global::System.DateTime _BirthDay;
        partial void OnBirthDayChanging(global::System.DateTime value);
        partial void OnBirthDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "FK_accounts", "emails")]
        public email email1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<email>("Entity.FK_accounts", "emails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<email>("Entity.FK_accounts", "emails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<email> email1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<email>("Entity.FK_accounts", "emails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<email>("Entity.FK_accounts", "emails", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "FK_AccountSecurityQuestions", "accountsecurityquestions")]
        public EntityCollection<accountsecurityquestion> accountsecurityquestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<accountsecurityquestion>("Entity.FK_AccountSecurityQuestions", "accountsecurityquestions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<accountsecurityquestion>("Entity.FK_AccountSecurityQuestions", "accountsecurityquestions", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="accountsecurityquestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accountsecurityquestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accountsecurityquestion object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="accountID">Initial value of the AccountID property.</param>
        /// <param name="securityQuestionID">Initial value of the SecurityQuestionID property.</param>
        /// <param name="answer">Initial value of the Answer property.</param>
        public static accountsecurityquestion Createaccountsecurityquestion(global::System.Int32 id, global::System.Int32 accountID, global::System.Int32 securityQuestionID, global::System.String answer)
        {
            accountsecurityquestion accountsecurityquestion = new accountsecurityquestion();
            accountsecurityquestion.ID = id;
            accountsecurityquestion.AccountID = accountID;
            accountsecurityquestion.SecurityQuestionID = securityQuestionID;
            accountsecurityquestion.Answer = answer;
            return accountsecurityquestion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccountID
        {
            get
            {
                return _AccountID;
            }
            set
            {
                OnAccountIDChanging(value);
                ReportPropertyChanging("AccountID");
                _AccountID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountID");
                OnAccountIDChanged();
            }
        }
        private global::System.Int32 _AccountID;
        partial void OnAccountIDChanging(global::System.Int32 value);
        partial void OnAccountIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SecurityQuestionID
        {
            get
            {
                return _SecurityQuestionID;
            }
            set
            {
                OnSecurityQuestionIDChanging(value);
                ReportPropertyChanging("SecurityQuestionID");
                _SecurityQuestionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SecurityQuestionID");
                OnSecurityQuestionIDChanged();
            }
        }
        private global::System.Int32 _SecurityQuestionID;
        partial void OnSecurityQuestionIDChanging(global::System.Int32 value);
        partial void OnSecurityQuestionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Answer
        {
            get
            {
                return _Answer;
            }
            set
            {
                OnAnswerChanging(value);
                ReportPropertyChanging("Answer");
                _Answer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Answer");
                OnAnswerChanged();
            }
        }
        private global::System.String _Answer;
        partial void OnAnswerChanging(global::System.String value);
        partial void OnAnswerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "FK_AccountSecurityQuestions", "accounts")]
        public account account
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<account>("Entity.FK_AccountSecurityQuestions", "accounts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<account>("Entity.FK_AccountSecurityQuestions", "accounts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<account> accountReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<account>("Entity.FK_AccountSecurityQuestions", "accounts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<account>("Entity.FK_AccountSecurityQuestions", "accounts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "FK_AccountSecurityQuestions_SecurityQuestionID", "securityquestions")]
        public securityquestion securityquestion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<securityquestion>("Entity.FK_AccountSecurityQuestions_SecurityQuestionID", "securityquestions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<securityquestion>("Entity.FK_AccountSecurityQuestions_SecurityQuestionID", "securityquestions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<securityquestion> securityquestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<securityquestion>("Entity.FK_AccountSecurityQuestions_SecurityQuestionID", "securityquestions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<securityquestion>("Entity.FK_AccountSecurityQuestions_SecurityQuestionID", "securityquestions", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="blog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class blog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new blog object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="blogContent">Initial value of the BlogContent property.</param>
        public static blog Createblog(global::System.Int32 id, global::System.String blogContent)
        {
            blog blog = new blog();
            blog.ID = id;
            blog.BlogContent = blogContent;
            return blog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BlogContent
        {
            get
            {
                return _BlogContent;
            }
            set
            {
                OnBlogContentChanging(value);
                ReportPropertyChanging("BlogContent");
                _BlogContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BlogContent");
                OnBlogContentChanged();
            }
        }
        private global::System.String _BlogContent;
        partial void OnBlogContentChanging(global::System.String value);
        partial void OnBlogContentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="email")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class email : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new email object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="emailPrefix">Initial value of the EmailPrefix property.</param>
        public static email Createemail(global::System.Int32 id, global::System.String emailPrefix)
        {
            email email = new email();
            email.ID = id;
            email.EmailPrefix = emailPrefix;
            return email;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailPrefix
        {
            get
            {
                return _EmailPrefix;
            }
            set
            {
                OnEmailPrefixChanging(value);
                ReportPropertyChanging("EmailPrefix");
                _EmailPrefix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailPrefix");
                OnEmailPrefixChanged();
            }
        }
        private global::System.String _EmailPrefix;
        partial void OnEmailPrefixChanging(global::System.String value);
        partial void OnEmailPrefixChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "FK_accounts", "accounts")]
        public EntityCollection<account> accounts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<account>("Entity.FK_accounts", "accounts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<account>("Entity.FK_accounts", "accounts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="securityquestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class securityquestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new securityquestion object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="securityQuestion1">Initial value of the SecurityQuestion1 property.</param>
        public static securityquestion Createsecurityquestion(global::System.Int32 id, global::System.String securityQuestion1)
        {
            securityquestion securityquestion = new securityquestion();
            securityquestion.ID = id;
            securityquestion.SecurityQuestion1 = securityQuestion1;
            return securityquestion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecurityQuestion1
        {
            get
            {
                return _SecurityQuestion1;
            }
            set
            {
                OnSecurityQuestion1Changing(value);
                ReportPropertyChanging("SecurityQuestion1");
                _SecurityQuestion1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SecurityQuestion1");
                OnSecurityQuestion1Changed();
            }
        }
        private global::System.String _SecurityQuestion1;
        partial void OnSecurityQuestion1Changing(global::System.String value);
        partial void OnSecurityQuestion1Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "FK_AccountSecurityQuestions_SecurityQuestionID", "accountsecurityquestions")]
        public EntityCollection<accountsecurityquestion> accountsecurityquestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<accountsecurityquestion>("Entity.FK_AccountSecurityQuestions_SecurityQuestionID", "accountsecurityquestions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<accountsecurityquestion>("Entity.FK_AccountSecurityQuestions_SecurityQuestionID", "accountsecurityquestions", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="passwordExpiry">Initial value of the PasswordExpiry property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        public static user Createuser(global::System.Int32 id, global::System.String userName, global::System.String password, global::System.DateTime passwordExpiry, global::System.Boolean active)
        {
            user user = new user();
            user.ID = id;
            user.UserName = userName;
            user.Password = password;
            user.PasswordExpiry = passwordExpiry;
            user.Active = active;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PasswordExpiry
        {
            get
            {
                return _PasswordExpiry;
            }
            set
            {
                OnPasswordExpiryChanging(value);
                ReportPropertyChanging("PasswordExpiry");
                _PasswordExpiry = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PasswordExpiry");
                OnPasswordExpiryChanged();
            }
        }
        private global::System.DateTime _PasswordExpiry;
        partial void OnPasswordExpiryChanging(global::System.DateTime value);
        partial void OnPasswordExpiryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion
    
    }

    #endregion
    
}
